### PR TITLE
fix the warning from the jrl-cmakemodules export

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description

[//]: # "Description of what you did.  If it is more complex, consider to add a"
[//]: # "'Summary' section."

Prevent warning from jrl_cmakemodule export Config,cmake modules

## How I Tested

[//]: # "Explain how you tested your changes"

I ran cmake on the BLMC_ROBOTS project

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [x] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [x] All new functions/classes are documented and existing documentation is updated according to changes.
- [x] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

### CODE REVIEW

**Comment by vincentberenz** [comment]
I will have to confess: I do not understand what this is about - - ;

**Comment by jviereck** [comment]
me neither...

**Comment by MaximilienNaveau** [comment]
Arf! Sorry it is a solution for the cmake warning sent by the `jrl_cmakemodules` (LAAS equivalent of the `mpi_cmake_module`).
It expects that the macro `CHECK_MINIMAL_CXX_STANDARD` exists otherwise send a warning.

It is particularly annoying as the warning is propagated through the dependencies.
hence evry package depending on either `master_board_sdk` or `odri_control_interface` will print this warning during cmake configuration time.

**Comment by MaximilienNaveau** [comment]
BTW it does not work properly...

**Comment by vincentberenz** [comment]
some more background : why does mpi-cmake-modules need to fix this ? What is the relation between mpi-cmake-modules and jrl-cmakemodules ? They are part of the same treep project ? Or we have some libraries which links against something related to jrl-cmakemodules ?

**Pull request closed without merging**
